### ISSUE TITLE
Restart build handler should send "org" parameter based on visibility of the repo

### ISSUE THREAD

**Issue by tanya-coding** [atomist-rugs/travis-handlers#8]
@tanya-coding commented on [Tue Mar 07 2017](https://github.com/atomist/github-rugs/issues/6)

Currently build handler doesn't pre-populate "org" parameter so bot ends up using default ".org" which is not correct for all organizations.  Handler should instead use repo information and populate the parameter.  This will likely require changes in model as well.

cc: @cdupuis @whostolebenfrog  

---

@whostolebenfrog commented on [Tue Mar 07 2017](https://github.com/atomist/github-rugs/issues/6#issuecomment-284767614)

> This will likely require changes in model as well

To be specific this information isn't currently recorded on a repo. Also need to take into account that repos might move between public and private.

An alternative is that we do currently have `build_url` available on the build itself which would work right now with no model changes.

---

@kipz commented on [Wed Mar 22 2017](https://github.com/atomist/github-rugs/issues/6#issuecomment-288498385)

Shouldn't this be another MappedParameter @tanya-coding ?

---

@tanya-coding commented on [Tue Apr 11 2017](https://github.com/atomist/github-rugs/issues/6#issuecomment-293371383)

@kipz bot doesn't really know if it should use ".org" or ".com" for a given repo, seems like handler should be able to make that determination based on model it loads.

**Comment by ddgenome** [comment]
With the GitHub token all the Travis Rug functions use, we should be able to query the GitHub API and determine this, thereby eliminating the need for this poorly named parameter.

https://developer.github.com/v3/repos/#get

In other words, it should not require any changes to the model.

**Comment by ddgenome** [comment]
Looking at this more closely, since the repo owner and name are not parameters to the restart build handler, we cannot look up the repo visibility. Do you think it would be better to continue to require the "org", now "visibility", parameter or remove it and require repo owner and name? Either way, whatever is calling the command handler will need to determine them. If we go the repo owner/name, we can use mapped parameters, but since the main use for this is in buttons on failed build lifecycle messages, I'm not sure what is easier/better.

**Comment by tanya-coding** [comment]
Lifecycle handler should already know owner/repo name information and it could include those as provided parameters for Restart Build action - that way bot will simply return them back when action is invoked.  Will that work?

**Comment by ddgenome** [comment]
Yes, that should work.

**Comment by ddgenome** [comment]
rug-functions-travis 0.16.0 has been released, so I can start on this.

**Comment by ddgenome** [comment]
This is all working now. Perhaps we can pair on releasing this new version and updating the build lifecycle message to use the latest version.

**Comment by ddgenome** [comment]
Maybe I should just change rug-functions-travis restart-travis-build to take the repo and owner so we can benefit from retrying GitHub and all the interfaces can be consistent.
